#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

touch smarthost.env

# Enable and restart the services

systemctl --user enable meeting-2024-app.service
systemctl --user restart meeting-2024-app.service

systemctl --user enable database.service
systemctl --user restart database.service
