#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from urllib.parse import urlparse

app_url = os.getenv("APP_URL")
domain = urlparse(app_url).netloc if app_url else None

config = {
    "domain": domain,
    "timezone": os.getenv("APP_TIMEZONE")
}

json.dump(config, fp=sys.stdout)
